import { test, expect } from '@playwright/test'
test('A06 A07 A10 A23 live discovery, linked selection and replay',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/swarm')
  await expect(page.locator('.connection')).toHaveText('● CONNECTED')
  const before=await page.request.get('/api/v1/swarm/health');expect(before.ok()).toBeTruthy()
  const title='Browser acceptance '+Date.now()
  const discovered=await page.request.post('/api/v1/swarm/commands/execute',{data:{action:'discover',idempotency_key:crypto.randomUUID(),payload:{title}}})
  expect(discovered.ok()).toBeTruthy();const result=await discovered.json()
  await page.getByRole('button',{name:'Content Universe',exact:false}).click()
  await page.getByRole('row').filter({hasText:title}).click()
  await expect(page.getByTestId('object-inspector')).toContainText(result.object.id)
  await expect(page.getByTestId('time-rail')).toContainText(title)
  await page.getByRole('button',{name:'Explore Around ↗',exact:true}).click()
  await expect(page.getByRole('img',{name:'Selected object relationship graph'}).or(page.locator('svg.graph'))).toBeVisible()
  await expect(page.locator('svg.graph circle.selected')).toHaveCount(1)
  const event=await page.request.get('/api/v1/swarm/objects/'+result.object.id+'/timeline')
  const at=(await event.json())[0].timestamp
  await page.getByLabel('Replay timestamp').fill(at)
  await page.getByRole('button',{name:'Replay',exact:true}).click()
  await expect(page.locator('.replay-banner')).toBeVisible()
  await expect(page.getByRole('button',{name:'＋ Discover test video'})).toBeDisabled()
  await expect(page.getByTestId('object-inspector')).toContainText('DISCOVERED')
  await page.screenshot({path:'../test-evidence/command-center.png',fullPage:true})
  await page.getByRole('button',{name:'Go live',exact:true}).click()
  await expect(page.locator('.replay-banner')).toHaveCount(0)
  // Offline/online forces reconnect; a new event must arrive in the activity stream.
  await page.context().setOffline(true)
  await page.context().setOffline(false)
  await expect(page.locator('.connection')).toHaveText('● CONNECTED')
  expect(errors).toEqual([])
})
